name: ligo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26
  - scipy=1.11
  - matplotlib=3.7
  - h5py=3.10
  - decorator=5.1
  - ipykernel=6
  - jupyterlab=4
  - pip
